# .github/workflows/scheduled-builds.yml
name: Trigger after 5 min

on:
  schedule:
    # Runs "at minute 5 past every hour" (see https://crontab.guru)
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Trigger 
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: >
         echo "Success"
